name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "93167d120ed646fc81f596a5b60676dd" }
]

[triggers]
crons = [ ]
